import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import java.awt.CardLayout;
import javax.swing.Box;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JButton;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ömer
 */
public class Credits extends Menu {
	private JLabel label;
	private JLabel label_1;
	private JLabel label_2;
	private JLabel label_3;

    /**
     * Creates new form Credits
     */
    public Credits() {
    	getContentPane().setLayout(null);
    	
    	label = new JLabel();
    	label.setText("Produced by");
    	label.setFont(new Font("Britannic Bold", Font.BOLD, 36));
    	label.setBounds(0, 11, 241, 36);
    	getContentPane().add(label);
    	
    	label_1 = new JLabel();
    	label_1.setText("Sekip Kaan Ekin");
    	label_1.setFont(new Font("Britannic Bold", Font.BOLD, 24));
    	label_1.setBounds(0, 67, 241, 24);
    	getContentPane().add(label_1);
    	
    	label_2 = new JLabel();
    	label_2.setText("Ali Can Zeybek");
    	label_2.setFont(new Font("Britannic Bold", Font.BOLD, 24));
    	label_2.setBounds(0, 70, 170, 92);
    	getContentPane().add(label_2);
    	
    	label_3 = new JLabel();
    	label_3.setText("Omer Faruk Geredeli");
    	label_3.setFont(new Font("Britannic Bold", Font.BOLD, 24));
    	label_3.setBounds(0, 107, 241, 92);
    	getContentPane().add(label_3);
    	
    	JButton jButton1 = new JButton("back To Main Menu");
    	jButton1.setFont(new java.awt.Font("Britannic Bold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 32, 32));
        jButton1.setText("back To Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 240, 250, 27);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GameManager.Instance.changeUI("MainMenu");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credits().setVisible(true);
            }
        });
    }
}
